# SweetDependency project configuration file
# You can adjust your custom configuration to your liking here
# You can visit https://github.com/HighCapable/SweetDependency for more help
#
# SweetDependency 项目配置文件
# 你可以在这里调整你喜欢的自定义配置
# 你可以前往 https://github.com/HighCapable/SweetDependency 以获得更多帮助

preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  maven-xposed:
    url: https://api.xposed.info/

plugins:
  com.android.application:
    version: 8.1.1
  org.jetbrains.kotlin.android:
    version: 1.9.10
  com.google.devtools.ksp:
    version: 1.9.10-1.0.13

libraries:
  de.robv.android.xposed:
    api:
      version: 82
  com.highcapable.yukihookapi:
    api:
      version: 1.1.11
    ksp-xposed:
      version: 1.1.11
  androidx.palette:
    palette-ktx:
      version: 1.0.0
  androidx.compose.material3:
    material3:
      version: 1.1.1
  org.jetbrains.kotlinx:
    kotlinx-coroutines-android:
      version: 1.7.3
  androidx.annotation:
    annotation:
      version: 1.7.0